 name: Hello World

on:
  push:
    branches:
      - hnaiskar-sketchy-patch-1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: |
          echo "This is first line"
          echo "This is line number 2"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Step
        run: echo "Running test cases"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: echo "Deploy the app"
