name: Hello World

on:
  push:
    branches:
      - hnaiskar-sketchy-patch-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hello Step
        run: |
          echo "This is first line"
          echo "This is line number 2"
